### ISSUE TITLE
example app doesn't work

### ISSUE THREAD

**Issue by ICEDLEE337** [pivotal-cf/cf-redis-example-app#3]
Trying to run the `create-service` command per the README results in an error:

`MACC02PT1PHG8WP:cf-redis-example-app lee$ cf create-service p-redis development redis`
`Creating service instance redis in org Project-Sapphire / space CDChimay as lee.norris@philips.com...`
`FAILED`
`Service offering p-redis not found`
`MACC02PT1PHG8WP:cf-redis-example-app lee$`

**Comment by tekknikk** [comment]
what did you call you redis service when you created the broker using cf?  try 'cf service-access' or cf service-brokers' do get your service name.

**Comment by ICEDLEE337** [comment]
Honestly I don't remember. I copied the example verbatim and it didn't work. In either case, I've moved on, so I'm closing the issue. Thanks for getting back to me though.
