### ISSUE TITLE
Test app redis-example-app failing to push with ruby_buildpack v1.8.50

### ISSUE THREAD

**Issue by pivotal-carlos-vasquez** [pivotal-cf/cf-redis-example-app#43]
A customer reported that the Redis tile errands are failing to push the test application with Ruby Buildpack 1.8.50 but not with 1.8.48. I confirmed with the lab environment above that this is indeed failing. A comparison in the push shows a different bundler dependency in use between the two different versions of the ruby buildpack. Ruby buildpack 1.8.50 is using bundler 1.17.2 and ruby buildpack 1.8.48 is using bundler 1.17.3. Odd that the older BP is using a newer dependency. The redis-example-app fails to push.

**Comment by carlosinfante98** [comment]
This issue was resolved. Now the BUNDLE_WITH line and .bundle directory are deleted.
