### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by tgeek77** [pivotal-cf/cf-redis-example-app#8]
You can't restage the app if it hasn't been staged the first time:

```
> cf restage redis-example-app
Restaging app redis-example-app in org lab / space exercises as admin...

Staging app and tracing logs...
App has not finished staging
FAILED
```

**Comment by edwardecook** [comment]
Hi @tgeek77, my understanding is that `cf restage` not succeeding unless the app has already been started is a quirk of `cf`. Was this done via `cf push --no-start`?

**Comment by edwardecook** [comment]
Hi @tgeek77, closing this for now, if you have any questions related to this please feel free to reopen and provide additional details.
